FONT_MAIN = "Segoe UI" 

COLOR_BG_APP = "#F1F5F9"       
COLOR_BG_CARD = "#FFFFFF"      
COLOR_PRIMARY = "#2563EB"      
COLOR_PRIMARY_LIGHT = "#EFF6FF"
COLOR_TEXT_MAIN = "#0F172A"    
COLOR_TEXT_SUB = "#64748B"     
COLOR_BORDER = "#E2E8F0"